name: CI

on: workflow_dispatch

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clone repository
        run:
          git clone https://github.com/Polusa1007/github_action.git
          cd github_action
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
