name: API Testing with Mock

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 步驟 1: 檢出你的代碼
    - name: Checkout repository
      uses: actions/checkout@v3

    # 步驟 2: 設定 Python 環境
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 你可以選擇任意支持的 Python 版本

    # 步驟 3: 快取 pip 安裝的依賴
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # 步驟 4: 安裝依賴
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 步驟 5: 運行測試
    - name: Run API tests
      run: |
        pytest
